### PR TITLE
Fix mypy 1.1.1 integration error of PR #656

### PR DESCRIPTION
**Pull request by berkaygunduzz**
Specified argument's keywords when using string classes defined in 'floss/results'

### CODE REVIEW

**Comment by berkaygunduzz** [comment]
As I forgot to mention, the test code `mypy --config-file .github/mypy/mypy.ini floss/ scripts/ tests/` works without any error and finishes with `Success: no issues found in 36 source files`. That's how I tested whether the solution works or not.

**Comment by williballenthin** [comment]
would you confirm this fixes all issues identified by using the flag `--check-untyped-defs` as well?

**Comment by berkaygunduzz** [comment]
Working on it

**Comment by mr-tz** [comment]
Can you change the PR to merge into master so our CI tests run?

**Comment by mr-tz** [comment]
black isn't happy with the code style:
```
Run black -l 120 --check .
would reformat /home/runner/work/flare-floss/flare-floss/floss/stackstrings.py
would reformat /home/runner/work/flare-floss/flare-floss/floss/strings.py
would reformat /home/runner/work/flare-floss/flare-floss/floss/tightstrings.py
```

Can you please check and then we can see about mypy.

**Comment by mr-tz** [comment]
#720 supersedes this, thanks for getting us started here!

**Pull request closed without merging**
