### PR TITLE
Update to new viv-utils API

### PR DESCRIPTION
**Pull request by mr-tz**
Plus some minor improvements

TODO: this depends on new viv-utils release.

### CODE REVIEW

**Review by williballenthin — APPROVED** [review]

**Comment by williballenthin** [comment]
shall i do a viv-utils release now? or hold off for any reason?

**Comment by mr-tz** [comment]
yes, please, we should be good

**Comment by williballenthin** [comment]
https://pypi.org/project/viv-utils/0.7.1/

**Comment by mr-tz** [comment]
Thank you! 🙇

**Pull request merged**
