### PR TITLE
Moving sigs directory and add MANIFEST-file

### PR DESCRIPTION
**Pull request by 3c7**
Potential fix for #560, hope i haven't overlooked any hardcoded `sigs` paths.

- Moved `sigs` to `floss` directory
- Addes MANIFEST.in file to include README, LICENSE and sigs

### CODE REVIEW

**Comment by mr-tz** [comment]
Thanks for the solution idea. To make the tool easy to use it makes a lot of sense to include the signatures in the default installation. I'll investigate this more this week.

**Comment by mr-tz** [comment]
Can we accomplish the same and leave `sigs` where it currently resides?

**Comment by 3c7** [comment]
I don't think so (but am not 100% sure - not super familiar with including non-source files in python modules). During installation, only the `floss` directory will be installed into the `site-packages` directory. While the other files and directories can be included in the distribution files, they will be skipped during installation.

**Comment by mr-tz** [comment]
Thanks, that makes sense. We can move the directory.

**Comment by mr-tz** [comment]
handled via #578

**Pull request closed without merging**
