### PR TITLE
Package signatures

### LINKED ISSUE #560: sigs does not exist or cannot be accessed
Basic install with pip and I get the following error:

```
OSError: signatures path .../envs/py37/lib/python3.7/site-packages/floss/../sigs does not exist or cannot be accessed
```

See same issue in capa at https://github.com/mandiant/capa/issues/682

### PR DESCRIPTION
**Pull request by mr-tz**
closes #560
based on  #561

### CODE REVIEW

**Comment by mr-tz** [comment]
@3c7 does this solution based on your PR work for you?

**Comment by 3c7** [comment]
It works! However, `python3 setup.py build` raises an error because `floss.sigs` is not registered as a package. This can be fixed through adding `floss.sigs` as a package

*setup.py*
```python
packages=setuptools.find_packages().append("floss.sigs"),
```

or adding an empty `__init__.py` file into `floss/sigs`.

I'm not sure, if this is relevant, as the installation via `pip install git+https://github.com/mr-tz/flare-floss@pkg/signatures` also works flawlessly.

**Comment by mr-tz** [comment]
Hm, for me `python setup.py build` seems to include the files?

```
...
copying floss\sigs\1_flare_msvc_rtf_32_64.sig -> build\lib\floss\sigs
copying floss\sigs\2_flare_msvc_atlmfc_32_64.sig -> build\lib\floss\sigs
copying floss\sigs\3_flare_common_libs.sig -> build\lib\floss\sigs
...
```

**Comment by 3c7** [comment]
Don't you get the below warning?

```
    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'floss.sigs' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'floss.sigs' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).
```

However, for now the package works as-is.

**Comment by mr-tz** [comment]
I did get the warning after updating `setuptools`. Thank you. How about now?

**Comment by 3c7** [comment]
Yep, that did the trick. Working as expected now.

**Comment by mr-tz** [comment]
Thank you very much. I'll create a new release.

**Pull request merged**
