### PR TITLE
improve Rust identification

### PR DESCRIPTION
**Pull request by mr-tz**

### CODE REVIEW

**Review by Arker123 — COMMENTED** [review]
Considering the reliability, wouldn't prioritizing hash searches over strings be a more robust approach?

**Review by williballenthin — APPROVED** [review]

**Comment by mr-tz** [comment]
What do you mean by reliability?

**Comment by Arker123** [comment]
I meant that when considering reliability, I thought prioritizing hash searches over strings might be more robust. My intuition is that the string 'rust<version>' could appear in many files, whereas hashes are likely to be more unique. What are your thoughts?

**Comment by mr-tz** [comment]
I think it's fairly robust. If we encounter issues we can come back to it.

**Pull request merged**
