### PR TITLE
Update build.yml

### PR DESCRIPTION
**Pull request by ggold7046**
Updated deprecated Actions.

### CODE REVIEW

**Comment by mr-tz** [comment]
2023-02-28_14-33-11_firefox

We should also tackle these warnings.

**Comment by ggold7046** [comment]
Hi @mr-tz , could you guide me how to tackle those warnings ?

**Comment by mr-tz** [comment]
See https://github.com/mandiant/capa/pull/1295/files for some hints. The PR also references a service one can use.

**Review by williballenthin — APPROVED** [review]

**Review by mr-tz — CHANGES_REQUESTED** [review]
There's still a warning: `Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/upload-artifact@v2`

**Comment by mr-tz** [comment]
Awesome, thank you!

**Pull request merged**
